assets/urls.py
from django.urls import path, include
from . import views

app_name = 'assets'

urlpatterns = [
    path('', views.AssetListView.as_view(), name='list'),
    path('create/', views.AssetCreateView.as_view(), name='create'),
    path('<int:pk>/', include([
        path('detail/', views.AssetDetailView.as_view(), name='detail'),
        path('update/', views.AssetUpdateView.as_view(), name='update'),
        path('delete/', views.AssetDeleteView.as_view(), name='del'),
    ])),
]

jms/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('assets/', include('assets.urls')),
    path('perms/', include('perms.urls')),
]

assets/models.py
from django.db import models

class Asset(models.Model):
    OS_Choice = [
        ('C', 'CentOS'),
        ('U', 'Ubuntu'),
        ('D', 'Debian'),
        ('R', 'Redhat'),
        ('B', 'BSD'),
    ]
    hostname = models.CharField(unique=True, max_length=128, verbose_name='Hostname')
    ip = models.GenericIPAddressField(verbose_name='IP', unique=True)
    port = models.IntegerField(default=22, verbose_name='端口')
    username = models.CharField(max_length=20, verbose_name='管理用户名')
    password = models.CharField(max_length=32, verbose_name='密码')
    os = models.CharField(choices=OS_Choice, max_length=2, verbose_name='系统平台')
    is_active = models.BooleanField(default=True, verbose_name='激活')

    def __str__(self):
        return self.hostname

assets/views.py
from django.urls import reverse_lazy
from users.mixins import LoginRequiredMixin
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import Asset
from .form import AssetForm


class AssetListView(LoginRequiredMixin, ListView):
    model = Asset
    context_object_name = 'assets'
    template_name = 'assets/list.html'


class AssetCreateView(LoginRequiredMixin, CreateView):
    model = Asset
    form_class = AssetForm
    template_name = 'assets/create.html'
    success_url = reverse_lazy('assets:list')


class AssetDetailView(LoginRequiredMixin, DetailView):
    model = Asset
    context_object_name = 'asset'
    template_name = 'assets/detail.html'


class AssetUpdateView(LoginRequiredMixin, UpdateView):
    model = Asset
    form_class = AssetForm
    template_name = 'assets/update.html'
    success_url = reverse_lazy('assets:list')


class AssetDeleteView(LoginRequiredMixin, DeleteView):
    model = Asset
    template_name = 'assets/create.html'
    success_url = reverse_lazy('assets:list')

assets/templates/assets/create.html
{% extends 'base.html' %}
{% block title %}资产管理{% endblock %}
{% block css %}
    .icon:hover{
    color: red;
    }
{% endblock %}
{% block content %}
    <h1 class="ui header">资产添加</h1>
    {% if form.errors %}
    <div class="ignored error ui message">
        {{ form.errors }}
    </div>
    {% endif %}
    <form class="ui form" method="post" action="">
        {% csrf_token %}
        {% for field in form %}
            <div class="field">
                {{ field.label_tag }}
                {{ field }}
            </div>
        {% endfor %}
        <button class="ui button" type="submit">Submit</button>
    </form>
{% endblock %}

assets/templates/assets/detail.html
{% extends 'base.html' %}
{% block title %}资产管理{% endblock %}
{% block css %}
    .icon:hover{
    color: red;
    }
{% endblock %}
{% block content %}
<h1 class="ui header">资产详情</h1>
    <table class="ui striped table">
        <thead>
        <tr>
            <th>主机名</th>
            <th>IP</th>
            <th>端口</th>
            <th>管理账号</th>
            <th>系统</th>
            <th>Active</th>
            <th>操作</th>
        </tr>
        </thead>
        <tbody>
        <tr {% if not asset.is_active %} class="error" {% endif %}>
            <td>{{ asset.hostname }}</td>
            <td>{{ asset.ip }}</td>
            <td>{{ asset.port }}</td>
            <td>{{ asset.username }}</td>
            <td>{{ asset.get_os_display }}</td>
            {% if not asset.is_active %}
                <td class="error"><i class="remove icon"></i></td>
            {% else %}
                <td class="aligned">
                    <i class="green checkmark icon"></i>
                </td>
            {% endif %}
            <td>
                <a href="{% url 'assets:update' asset.id %}"><i class="edit icon"></i></a>
            </td>
        </tr>
        </tbody>
    </table>

{% endblock %}

assets/templates/assets/list.html
{% extends 'base.html' %}
{% block title %}资产管理{% endblock %}
{% block css %}
    .icon:hover{
    color: red;
    }
{% endblock %}
{% block content %}
    <a class="ui right floated small teal labeled button" id="asset_add_btn" href="{% url 'assets:create' %}"> 添加资产 </a>
    <h1 class="ui header">资产列表</h1>
    <table class="ui striped table">
        <thead>
        <tr>
            <th>主机名</th>
            <th>IP</th>
            <th>端口</th>
            <th>管理账号</th>
            <th>系统</th>
            <th>Active</th>
            <th>操作</th>
        </tr>
        </thead>
        <tbody>
        {% for asset in assets %}
            <tr {% if not asset.is_active %} class="error" {% endif %}>
                <td>{{ asset.hostname }}</td>
                <td>{{ asset.ip }}</td>
                <td>{{ asset.port }}</td>
                <td>{{ asset.username }}</td>
                <td>{{ asset.get_os_display }}</td>
                {% if not asset.is_active %}
                    <td class="error"><i class="remove icon"></i></td>
                {% else %}
                    <td class="aligned">
                        <i class="green checkmark icon"></i>
                    </td>
                {% endif %}
                <td>
                    <i class="remove asset icon" href="{% url 'assets:del' asset.id %}"></i>
                    <a href="{% url 'assets:update' asset.id %}"><i class="edit icon"></i></a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <div class="ui small modal transition hidden">
        <i class="close icon"></i>
        <div class="header">
            添加用户
        </div>

        <div class="content">
            <form class="ui form" method="post" action="{% url 'assets:create' %}">
                {% csrf_token %}
                {% for field in form %}
                    <div class="field">
                        {{ field.label_tag }}
                        {{ field }}
                    </div>
                {% endfor %}
                <button class="ui button" type="submit">Submit</button>
            </form>
        </div>
    </div>
{% endblock %}

{% block script %}
    <script>
        $(document).ready(function () {
            var csrftoken = Cookies.get('csrftoken');

            function csrfSafeMethod(method) {
                // these HTTP methods do not require CSRF protection
                return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
            }

            $.ajaxSetup({
                beforeSend: function (xhr, settings) {
                    if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                        xhr.setRequestHeader("X-CSRFToken", csrftoken);
                    }
                }
            });

            $('.remove.asset').click(function () {
                var url = $(this).attr('href');
                if (confirm('确定删除')) {
                    $.post(
                        url,
                        function () {
                            console.log('删除用户成功');
                            location.reload()
                        }
                    )
                }
            });
        })
    </script>
{% endblock %}

assets/templates/assets/update.html
{% extends 'base.html' %}
{% block title %}资产更新{% endblock %}
{% block css %}
    .icon:hover{
    color:red;
    }
{% endblock %}
{% block content %}
    <h1 class="ui header">资产详情</h1>
    {% if form.errors %}
        <div class="ignored error ui message">
            {{ form.errors }}
        </div>
    {% endif %}
    <form class="ui form" method="post" action="">
        {% csrf_token %}
        {% for filed in form %}
            <div class="ui field">
                {{ filed.label_tag }}
                {{ filed }}
            </div>
        {% endfor %}
        <button class="ui button" type="submit">Submit</button>
    </form>
{% endblock %}