assets/urls.py
from django.urls import path, include
from . import views

app_name = 'assets'

urlpatterns = [
    path('', views.AssetListView.as_view(), name='list'),
    path('create/', views.AssetCreateView.as_view(), name='create'),
    path('<int:pk>/', include([
        path('detail/', views.AssetDetailView.as_view(), name='detail'),
        path('update/', views.AssetUpdateView.as_view(), name='update'),
        path('delete/', views.AssetDeleteView.as_view(), name='del'),
    ])),
]

jms/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('assets/', include('assets.urls')),
    path('perms/', include('perms.urls')),
]

perms/urls.py
from django.urls import path, include
from . import views

app_name = 'perms'

urlpatterns = [
    path('', views.PermListView.as_view(), name='list'),
    path('create/', views.PermCreateView.as_view(), name='create'),
    path('<int:pk>/', include([
        path('detail/', views.PermDetailView.as_view(), name='detail'),
        path('delete/', views.PermDeleteView.as_view(), name='del'),
    ])),
]

users/urls.py
from django.urls import path, include
from . import views

app_name = 'users'

urlpatterns = [
    path('', views.user_list, name='list'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('add/', views.user_add, name='add'),
    path('<int:pk>/', include([
        path('update/', views.user_update, name='update'),
        path('detail/', views.user_detail, name='detail'),
        path('del/', views.user_del, name='del'),
    ])),
]

templates/base.html
{% load static %}
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <title>
        {% block title %}
        {% endblock %}
    </title>
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'semantic/semantic.min.css' %}">
    <script src="{% static 'semantic/semantic.min.js' %}"></script>
    <script src="{% static 'js/js.cookie.js' %}"></script>
    <style type="text/css">
        body {
            background-color: #FFFFFF;
        }
        .ui.menu .item img.logo {
            margin-right: 1.5em;
        }
        .main.container {
            margin-top: 7em;
        }
        .wireframe {
            margin-top: 2em;
        }
        .ui.footer.segment {
            margin: 5em 0em 0em;
            padding: 5em 0em;
        }
        .ui.text.container {
            font-family: Lato,'Helvetica Neue',Arial,Helvetica,sans-serif;
            max-width: 80%!important;
            line-height: 1.5;
            font-size: 1.14285714rem;
        }
        {% block css %}
        {% endblock %}
  </style>
</head>
<body>
    <div class="ui fixed inverted menu">
        <div class="ui container">
            <a href="#" class="header item">
              <img class="logo" src="{% static 'img/logo.png' %}">
              JMS
            </a>
            <a href="{% url 'users:list' %}" class="item">用户</a>
            <a href="{% url 'assets:list' %}" class="item">资产</a>
            <a href="{% url 'perms:list' %}" class="item">授权</a>
            <div class="ui simple dropdown item">
                其它<i class="dropdown icon"></i>
                <div class="menu">
                    <a class="item" href="#">Link Item</a>
                    <a class="item" href="#">Link Item</a>
                    <div class="divider"></div>
                    <div class="header">Header Item</div>
                    <div class="item">
                        <i class="dropdown icon"></i>
                        Sub Menu
                        <div class="menu">
                            <a class="item" href="#">Link Item</a>
                            <a class="item" href="#">Link Item</a>
                        </div>
                    </div>
                    <a class="item" href="#">Link Item</a>
                </div>
            </div>
            <div class="right menu">
                <div class="item">
                  <div class="ui transparent inverted icon input">
                    <i class="search icon"></i>
                    <input type="text" placeholder="Search">
                  </div>
                </div>
                <div class="ui simple dropdown item">
                {{ request.user.username }} <i class="dropdown icon"></i>
                <div class="menu">
                    <a class="item" href="{% url 'users:logout' %}">登出</a>
                </div>
            </div>
            </div>
        </div>
    </div>

    <div class="ui main text container">
        {% block content %}
        {% endblock %}
    </div>

    <div class="ui inverted vertical footer segment">
        <div class="ui center aligned container">
            <div class="ui stackable inverted divided grid">
            </div>
            <img src="{% static 'img/logo.png' %}" class="ui centered mini image">
            <div class="ui horizontal inverted small divided link list">
                <a class="item" href="#">JMS</a>
                <a class="item" href="#">Contact Us</a>
                <a class="item" href="#">Terms and Conditions</a>
                <a class="item" href="#">Privacy Policy</a>
            </div>
        </div>
    </div>

</body>
{% block script %}
{% endblock %}
</html>