jms/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('assets/', include('assets.urls')),
    path('perms/', include('perms.urls')),
]

perms/urls.py
from django.urls import path, include
from . import views

app_name = 'perms'

urlpatterns = [
    path('', views.PermListView.as_view(), name='list'),
    path('create/', views.PermCreateView.as_view(), name='create'),
    path('<int:pk>/', include([
        path('detail/', views.PermDetailView.as_view(), name='detail'),
        path('delete/', views.PermDeleteView.as_view(), name='del'),
    ])),
]

perms/models.py
from django.db import models

from django.conf import settings
from assets.models import Asset


class Perm(models.Model):
    name = models.CharField(max_length=64, verbose_name='名称')
    user = models.ManyToManyField(settings.AUTH_USER_MODEL, verbose_name='用户')
    asset = models.ManyToManyField(Asset, verbose_name='资产')
    date_add = models.DateTimeField(auto_now_add=True)
    comment = models.CharField(max_length=128, blank=True, null=True)

    def __str__(self):
        return self.id

perms/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.http import HttpResponse
from django.views.generic.edit import SingleObjectMixin
from django.views.generic import ListView, DetailView, CreateView, View
from .models import Perm
from users.mixins import LoginRequiredMixin
from .form import PermForm


class PermListView(LoginRequiredMixin, ListView):
    model = Perm
    template_name = 'perms/list.html'
    form = PermForm()

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(PermListView, self).get_context_data()
        context['form'] = self.form
        return context


class PermDetailView(DetailView):
    model = Perm
    template_name = 'perms/detail.html'


class PermCreateView(LoginRequiredMixin, CreateView):
    model = Perm
    success_url = reverse_lazy('perms:list')
    form_class = PermForm

    def get(self, request, *args, **kwargs):
        return HttpResponse("Method not support", status=405)

    def form_invalid(self, form):
        return HttpResponse(";".join(form.errors), status=400)


class PermDeleteView(SingleObjectMixin, View):
    model = Perm

    def post(self, request, *args, **kwargs):
        perm = self.get_object()
        perm.delete()
        return HttpResponse("删除成功")

perms/templates/perms/detail.html
{% extends 'base.html' %}
{% block title %}授权详情{% endblock %}
{% block css %}
    .icon:hover{
        color: red;
    }
{% endblock %}
{% block content %}
    <h2>{{ object.name }}</h2>
    <div class="ui pointing secondary menu">
        <a class="item active" data-tab="first">用户</a>
        <a class="item" data-tab="second">资产</a>
    </div>
    <div class="ui tab segment active" data-tab="first">
        <table class="ui celled table">
            <thead>
            <tr>
                <th>姓名</th>
                <th>用户名</th>
                <th>Email</th>
            </tr>
            </thead>
            <tbody>
            {% for u in object.user.all %}
            <tr>
                <td>{{ u.name }}</td>
                <td>{{ u.username }}</td>
                <td>{{ u.email }}</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="ui tab segment" data-tab="second">
        <table class="ui celled table">
            <thead>
            <tr>
                <th>主机名</th>
                <th>IP</th>
                <th>端口</th>
            </tr>
            </thead>
            <tbody>
            {% for asset in object.asset.all %}
                <tr>
                    <td>{{ asset.hostname}}</td>
                    <td>{{ asset.ip }}</td>
                    <td>{{ asset.port }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}
{% block script %}
    <script>
        $('.ui.menu .item').tab();
    </script>
{% endblock %}

perms/templates/perms/list.html
{% extends 'base.html' %}
{% block title %}授权管理{% endblock %}
{% block css %}
    .icon:hover{
        color:red;
    }
{% endblock %}
{% block content %}
    <div class="ui right floated small teal labeled button" id="perm_add_btn">添加授权</div>
    <h1 class="ui header">授权列表</h1>
    <table class="ui striped table">
        <thead>
        <tr>
            <th>名称</th>
            <th>用户数量</th>
            <th>主机数量</th>
            <th>备注</th>
            <th>操作</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            {% for object in object_list %}
                <td>{{ object.name }}</td>
                <td>{{ object.user.count }}</td>
                <td>{{ object.asset.count }}</td>
                <td>{{ object.comment }}</td>
                <td>
                    <i class="perm del remove icon" href="{% url 'perms:del' object.id %}"></i>
                    <a href="{% url 'perms:detail' object.id %}"> <i class="arrow circle outline right icon"></i> </a>
                </td>
            {% endfor %}
        </tr>
        </tbody>
    </table>

    <div class="ui small modal transition hidden">
        <i class="close icon"></i>
        <div class="header">添加授权</div>

        <div class="content">
            <form class="ui form" method="post" action="{% url 'perms:create' %}">
                {% csrf_token %}
                {% for field in form %}
                    <div class="field">
                        {{ field.label_tag }}
                        {{ field }}
                    </div>
                {% endfor %}
                <button class="ui button" type="submit">Submit</button>
            </form>
        </div>
    </div>
{% endblock %}

{% block script %}
    <script>
        $(document).ready(function () {
            var csrftoken = Cookies.get('csrftoken');

            function csrfSafeMethod(method) {
                // these HTTP methods do not require CSRF protection
                return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
            }

            $.ajaxSetup({
                beforeSend: function (xhr, settings) {
                    if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                        xhr.setRequestHeader("X-CSRFToken", csrftoken);
                    }
                }
            });

            $('#perm_add_btn').click(function () {
                $('.small.modal').modal('show');
            });

            $('.perm.del').click(function () {
                var url = $(this).attr('href');
                if (confirm('确定删除')) {
                    $.post(
                        url,
                        function () {
                            console.log('删除成功');
                            location.reload()
                        }
                    )
                }
            });
        })
    </script>
{% endblock %}